//    uniCenta oPOS - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2013 uniCenta & previous Openbravo POS works
//    http://www.unicenta.net
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

report = new com.openbravo.pos.reports.PanelReportBean();

report.setTitleKey("Menu.SalesManagement");
report.setReport("/com/openbravo/reports/sales_hallmark");
report.setResourceBundle("com/openbravo/reports/products_messages");

report.setSentence("select TICKET, REFERENCE, PRODUCTS.NAME AS PRODUCTNAME, UNITS, PRICE, CASE COSTPRICE WHEN 0.0 THEN PRODUCTS.PRICEBUY ELSE COSTPRICE END AS COSTPRICE, (units * price) as LINENET, CASE COSTPRICE WHEN 0.0 THEN (units * PRODUCTS.PRICEBUY) ELSE (units * COSTPRICE) END as LINECOST, TAXCAT, PEOPLE.NAME AS PERSONNAME, DATENEW " +
                   " from receipts, tickets, ticketlines, products, people " +
                   " where receipts.id = tickets.id and tickets.id = ticketlines.ticket and ticketlines.product = products.id and tickets.person = people.id " +
                   " AND ?(QBF_FILTER) " +
                   " ORDER BY DATENEW ASC");

report.addParameter("RECEIPTS.DATENEW");
report.addParameter("RECEIPTS.DATENEW");
paramdates = new com.openbravo.pos.reports.JParamsDatesInterval();
paramdates.setEndDate(com.openbravo.beans.DateUtils.getToday());
report.addQBFFilter(paramdates);

report.addField("TICKET", com.openbravo.data.loader.Datas.STRING);
report.addField("REFERENCE", com.openbravo.data.loader.Datas.STRING);
report.addField("PRODUCTNAME", com.openbravo.data.loader.Datas.STRING);
report.addField("UNITS", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("PRICE", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("COSTPRICE", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("LINENET", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("LINECOST", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("TAXCAT", com.openbravo.data.loader.Datas.STRING);
report.addField("PERSONNAME", com.openbravo.data.loader.Datas.STRING);
report.addField("DATENEW", com.openbravo.data.loader.Datas.TIMESTAMP);

report;

