//    uniCenta oPOS - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2013 uniCenta & previous Openbravo POS works
//    http://www.unicenta.net
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

report = new com.openbravo.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Products");
report.setReport("/com/openbravo/reports/stock_value_hallmark");
report.setResourceBundle("com/openbravo/reports/products_messages");

report.setSentence("SELECT CATEGORIES.ID AS CATEGORY, CATEGORIES.NAME AS CATEGORYNAME, SUM(PRODUCTS.PRICEBUY) AS TOTALCOSTPRICE, SUM(PRODUCTS.PRICESELL) AS TOTALNETPRICE, SUM(CAST(PRODUCTS.STOCKVOLUME AS UNSIGNED)) AS STOCKVOLUME, TC.ID AS TAXCAT " +
                 "FROM PRODUCTS LEFT OUTER JOIN CATEGORIES ON PRODUCTS.CATEGORY = CATEGORIES.ID LEFT OUTER JOIN TAXCATEGORIES TC ON PRODUCTS.TAXCAT = TC.ID " +
                 "WHERE PRODUCTS.STOCKVOLUME > 0 " +
                 "GROUP BY CATEGORY " +
                 "ORDER BY CATEGORIES.NAME");

report.addField("CATEGORY", com.openbravo.data.loader.Datas.STRING);
report.addField("CATEGORYNAME", com.openbravo.data.loader.Datas.STRING);
report.addField("TOTALCOSTPRICE", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("TOTALNETPRICE", com.openbravo.data.loader.Datas.DOUBLE);
report.addField("STOCKVOLUME", com.openbravo.data.loader.Datas.INT);
report.addField("TAXCAT", com.openbravo.data.loader.Datas.STRING);

report;

